root = "."
tmp_dir = "tmp/air"

[build]
cmd = "go build -o ./tmp/air/moyi-admin ./cmd/server"
bin = "./tmp/air/moyi-admin"
full_bin = ""
include_ext = ["go", "toml", "env"]
exclude_dir = ["tmp", "legacy-hyperf", ".git"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = false
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 500
rerun = false
rerun_delay = 500

[log]
time = true
main_only = false
silent = false

[screen]
clear_on_rebuild = false
keep_scroll = true

[misc]
clean_on_exit = true
